version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-patch']
