sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
jobs:
  include:
    - stage: test
      script: npm run validate
    - stage: deploy
      node_js: 12
      script: node src travis-after-success
      if: branch = master AND type = push
